/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignmentq3;
//Import the BMI and Loan frames
import frames.BMIFrame;
import frames.loanFrame;

import java.io.*;
import java.net.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernard Heyns DV2013-0499
 */
//Create the class that extends Jframe
public class clientInterface extends javax.swing.JFrame {

    /**
     * Creates new form clientInterface
     */
    //The constructor initiates the components 
    public clientInterface() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPane = new javax.swing.JDesktopPane();
        bmiButton = new javax.swing.JButton();
        loanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        bmiButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bmiButton.setText("BMI");
        bmiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmiButtonActionPerformed(evt);
            }
        });

        loanButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loanButton.setText("Loan Calculator");
        loanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
            .addComponent(deskPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bmiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //Create instances of the two interfaces
    BMIFrame bframe = new BMIFrame();
   loanFrame lframe = new loanFrame();
        
    private void bmiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmiButtonActionPerformed
        //Add the bmi frame to the deskPane
        deskPane.add(bframe,0);
        //Set the bmi frame visible and set the loan frame to not visible
        bframe.setVisible(true);
        lframe.setVisible(false);
    }//GEN-LAST:event_bmiButtonActionPerformed

    private void loanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanButtonActionPerformed
        //Add the loan frame to the deskPane
        deskPane.add(lframe,0);
        //Set the loan frame to visible and the BMI frame to not visible
        lframe.setVisible(true);
        bframe.setVisible(false);
       
        
    }//GEN-LAST:event_loanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //Set the decimal format to trim long calculated doubles
     DecimalFormat df = new DecimalFormat("#.##");
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientInterface().setVisible(true);
                
                
            }
        });
    }
    //Create the sendToServer method which takes an array of doubles and an int
    public void sendToServer(double[] ar, int o){
        try{
            DataInputStream input;
            DataOutputStream output;
            //Create a socket on the localhost on port 8090 to contact the server
        Socket socket = new Socket("localhost", 8090);
        //Create input and output streams
       input = new DataInputStream(socket.getInputStream());
       output = new DataOutputStream(socket.getOutputStream());
        //Check if the o is 1 which will write the values to the loan 
        if (o == 1){
            output.writeUTF("Loan");
        output.writeDouble(ar[0]);
        output.writeDouble(ar[1]);
       output.writeDouble(ar[2]);
     //else check if o is equal to 2 which means doubles are written to the BMI calculation
        }else if (o ==2){
            output.writeUTF("BMI");
            output.writeDouble(ar[0]);
            output.writeDouble(ar[1]);
            output.writeDouble(ar[2]); 
        }
        int clientNums;
        //Check which values are sent back from the server by checking the UTF and assigning it to String kind
        String kind = input.readUTF();

         if(kind.equals("Loan")){
             //Read the amount of clients and assign them
             clientNums = input.readInt();
                //The JOptionpane shows the calculated amount and which number of client they are
               JOptionPane.showMessageDialog(lframe,
   "SERVER RESPONSE " + "Your total loan repayment is:"+input.readDouble()+ "\n.Client number: "+clientNums);
         }else {
             //Read the amount of clients and assign them
             clientNums = input.readInt();
             // The JOptionPane shows a message to the client
                JOptionPane.showMessageDialog(bframe,
    "SERVER RESPONSE " + "Your BMI is:"+df.format(input.readDouble())+ "\n.Client number: "+clientNums);
         }
         //Close the connection and flush the output stream
            input.close();
            output.flush();
            
           
           
       
       
        
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmiButton;
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JButton loanButton;
    // End of variables declaration//GEN-END:variables
}
